spring:
  # 服务注册配置
  cloud:
    zookeeper:
      discovery:
        # 开启服务注册
        enabled: true
        # 服务路径
        root: "/star/services/stag"
        # 自动注册
        register: true
        # 使用ip地址注册微服务
        prefer-ip-address: true
        metadata:
          management.port: ${management.server.port}
          management.context-path: ${management.endpoints.web.basePath}
      connect-string: ""
      connection-timeout: 3000
      max-retries: 3
      max-sleep-ms: 500
    loadbalancer:
      # 启用负载均衡
      enabled: true
      cache:
        # 禁用lb缓存
        enabled: true
      retry:
        enabled: false
  # mvc配置
  mvc:
    log-request-details: true
    log-resolved-exception: false
  # 数据源配置
  datasource:
    url: ""
    username: ""
    password: ""
    # 启用hikari连接池
    hikari:
      # 自动提交
      auto-commit: true
      maximum-pool-size: 20
      minimum-idle: 10
      max-lifetime: 3600000
      pool-name: "hikari-database"
      # 开启jmx
      register-mbeans: true
  # jpa配置
  jpa:
    # jpa的数据库类型
    database: postgresql
    # jpa数据库方言配置
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"
    # 禁止启动项目执行ddl语句
    generate-ddl: true
    # 开启打印sql
    show-sql: false
    hibernate:
      # 仅验证ddl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
  # kafka配置
  kafka:
    bootstrap-servers:
      - ""
    consumer:
      auto-offset-reset: latest
  # redis配置
  redis:
    host: ""
    port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 20
        min-idle: 10
  elasticsearch:
    uris:
      - ""

springdoc:
  use-management-port: true
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true
  show-actuator: true

feign:
  # 开启res4j熔断
  circuitbreaker:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 30

remote:
  course: "http://tg-course-service-svc.tiangong-staging.svc.cluster.local"
  student: "http://tg-student-service-svc.tiangong-staging.svc.cluster.local"
  security: "http://tg-organization-service-svc.tiangong-staging.svc.cluster.local"
  coupon: "http://tg-coupon-service-svc.tiangong-staging.svc.cluster.local"